spring:
  application:
    name: payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ricardofood?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:senha123}
  jpa:
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081/eureka}
server:
  port: 0

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 10s
    instances:
      confirmPayment:
        waitDurationInOpenState: 50s

