spring:
  application:
    name: payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ricardofood?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:senha123}
  jpa:
    show-sql: true
